/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-11-11 05:17:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/include/../users/login_modal.jsp", Long.valueOf(1605066961199L));
    _jspx_dependants.put("jar:file:/C:/Users/82105/TIL/2020/October%202020/JSP/apache-tomcat-9.0.39/wtpwebapps/SpringWebMvcProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1603856516461L));
    _jspx_dependants.put("jar:file:/C:/Users/82105/TIL/2020/October%202020/JSP/apache-tomcat-9.0.39/wtpwebapps/SpringWebMvcProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <title>아이즈원츄~CHU~♡</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom fonts for this template -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" >\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" >\r\n");
      out.write("  \r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("  <script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  <!-- Plugin JavaScript -->\r\n");
      out.write("  <script src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Contact form JavaScript -->\r\n");
      out.write("  <script src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".music-menu {\r\n");
      out.write("\tbackground-color: #ff52a0;\r\n");
      out.write("\tborder: 1px solid #fffe2e;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".music-tap {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write(".music-tap:hover {\r\n");
      out.write("    background-color: #ff52a0;\r\n");
      out.write("    color: #F7FE2E;\r\n");
      out.write("    text-shadow: 5px 2px 2px black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover > .dropdown-menu { \r\n");
      out.write("    display: block;  \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-light fixed-top\" id=\"mainNav\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"/\">\r\n");
      out.write("      \t<img class=\"img-fluid\" src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" alt=\"\" style=\"width:130px; height:50px;\" />\r\n");
      out.write("      </a>\r\n");
      out.write("      <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\">\r\n");
      out.write("        메뉴\r\n");
      out.write("        <i class=\"fas fa-bars\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("        <ul class=\"navbar-nav text-uppercase ml-auto\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"/\">HOME</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\">INTRODUCE</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger dropdown-toggle\" data-toggle=\"dropdown\">MUSIC</a>\r\n");
      out.write("            <div class=\"dropdown-menu music-menu\"> \r\n");
      out.write("            \r\n");
      out.write("              <div class=\"dropdown dropright\">            \r\n");
      out.write("\t\t        <a class=\"dropdown-item dropdown-toggle music-tap\" data-toggle=\"dropdown\" style=\"color:white;\">COLOR*IZ</a>\r\n");
      out.write("\t\t\t    <div class=\"dropdown-menu music-menu\"> \r\n");
      out.write("\t\t\t      <a class=\"dropdown-item music-tap\" data-toggle=\"modal\" href=\"#lavieenrose\">La Vie En Rose MV</a>\r\n");
      out.write("\t\t\t      <a class=\"dropdown-item music-tap\" data-toggle=\"modal\" href=\"#lavieenrose-2\">La Vie En Rose 교차편집</a>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t      <div class=\"dropdown dropright\">            \r\n");
      out.write("\t\t        <a class=\"dropdown-item dropdown-toggle music-tap\" data-toggle=\"dropdown\" style=\"color:white;\">HEART*IZ</a>\r\n");
      out.write("\t\t\t    <div class=\"dropdown-menu music-menu\"> \r\n");
      out.write("\t\t\t      <a class=\"dropdown-item music-tap\" data-toggle=\"modal\" href=\"#violeta\">Violeta MV</a>\r\n");
      out.write("\t\t\t      <a class=\"dropdown-item music-tap\" data-toggle=\"modal\" href=\"#violeta-2\">Violeta 교차편집</a>\t\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      \t   \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\">BOARD</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav><br><br><br>\r\n");
      out.write("\r\n");
      out.write("  <!-- Header -->\r\n");
      out.write("  <header class=\"masthead\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"intro-text\">        \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 Modal-->\r\n");
      out.write("<div class=\"modal fade\" id=\"log-in\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: #ff52a0;\">IZONE</span> 로그인\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"#\" name=\"izone-sign-in\" method=\"post\" id=\"signInForm\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-bottom: 0;\">\r\n");
      out.write("\t\t\t\t\t<table style=\"cellpadding: 0; cellspacing: 0; margin: 0 auto; width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>아이디를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"idCheck\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"signInId\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control tooltipstered\" maxlength=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"최대 10자\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>비밀번호를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"pwCheck\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" size=\"17\" maxlength=\"20\" id=\"signInPw\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"userPw\" class=\"form-control tooltipstered\" \r\n");
      out.write("\t\t\t\t\t\t\t\tmaxlength=\"20\" required=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"ime-mode: inactive; margin-bottom: 25px; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"최소 8자\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-top: 10px; text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>로그인하셔서 WIZONE이 되어보세요~~!</strong></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 100%; text-align: center; colspan: 2;\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" value=\"로그인\" class=\"btn form-control tooltipstered\" id=\"signIn-btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: #ff52a0; margin-top: 0; height: 40px; color: white; border: 0px solid #f78f24; opacity: 0.8\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%; text-align: center; colspan: 2; margin-top: 24px; padding-top: 12px; border-top: 1px solid #ececec\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn form-control tooltipstered\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#sign-up\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"cursor: pointer; margin-top: 0; height: 40px; color: white; background-color: orange; border: 0px solid #388E3C; opacity: 0.8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td\tstyle=\"width: 100%; text-align: center; colspan: 2; margin-top: 24px; padding-top: 12px; border-top: 1px solid #ececec\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"custom-login-btn\" href=\"https://kauth.kakao.com/oauth/authorize?client_id=1b99bdb2b2d8b2b7b7f7c7ee8f97842b&redirect_uri=http://localhost:8181/ggbro/kakaoLogin&response_type=code\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"//mud-kage.kakao.com/14/dn/btqbjxsO6vP/KPiGpdnsubSq3a0PHEGUK1/o.jpg\" width=\"300\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 회원가입 Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"sign-up\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Modal content-->\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: #ff52a0;\">IZONE</span> 회원 가입\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"#\" name=\"signup\" id=\"signUpForm\" method=\"post\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-bottom: 0;\">\r\n");
      out.write("\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\tstyle=\"cellpadding: 0; cellspacing: 0; margin: 0 auto; width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>아이디를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"idChk\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"user_id\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control tooltipstered\" maxlength=\"14\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"숫자와 영어로 4-10자\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>비밀번호를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"pwChk\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" size=\"17\" maxlength=\"20\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"userPw\" class=\"form-control tooltipstered\" \r\n");
      out.write("\t\t\t\t\t\t\t\tmaxlength=\"20\" required=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"ime-mode: inactive; margin-bottom: 25px; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"영문과 특수문자를 포함한 최소 8자\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>비밀번호를 재확인해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"pwChk2\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" size=\"17\" maxlength=\"20\" id=\"password_check\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"pw_check\" class=\"form-control tooltipstered\" \r\n");
      out.write("\t\t\t\t\t\t\t\tmaxlength=\"20\" required=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"ime-mode: inactive; margin-bottom: 25px; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"비밀번호가 일치해야합니다.\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>이름을 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"nameChk\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"userName\" id=\"user_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control tooltipstered\" maxlength=\"6\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"한글로 최대 6자\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!--  \r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>이메일을 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"emailChk\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"email\" name=\"userEmail\" id=\"user_email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control tooltipstered\" \r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"ex) izone@produce.com\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t\t\t-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-top: 10px; text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>회원가입하셔서 WIZONE이 되어보세요~~!</strong></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 100%; text-align: center; colspan: 2;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" value=\"회원가입\" \r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn form-control tooltipstered\" id=\"signup-btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: #ff52a0; margin-top: 0; height: 40px; color: white; border: 0px solid #388E3C; opacity: 0.8\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//start JQuery\r\n");
      out.write("$(function() {\r\n");
      out.write("\t\r\n");
      out.write("\tconst getIdCheck= RegExp(/^[a-zA-Z0-9]{4,14}$/);\r\n");
      out.write("\tconst getPwCheck= RegExp(/([a-zA-Z0-9].*[!,@,#,$,%,^,&,*,?,_,~])|([!,@,#,$,%,^,&,*,?,_,~].*[a-zA-Z0-9])/);\r\n");
      out.write("\tconst getName= RegExp(/^[가-힣]+$/);\r\n");
      out.write("\tconst getMail = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/);\r\n");
      out.write("\tlet chk1 = false, chk2 = false, chk3 = false, chk4 = false;\r\n");
      out.write("\t\r\n");
      out.write("\t//회원가입 검증~~\r\n");
      out.write("\t//ID 입력값 검증.\r\n");
      out.write("\t$('#user_id').on('keyup', function() {\r\n");
      out.write("\t\tif($(\"#user_id\").val() === \"\"){\r\n");
      out.write("\t\t\t$('#user_id').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#idChk').html('<b style=\"font-size:14px;color:red;\">[아이디는 필수 정보에요!]</b>');\r\n");
      out.write("\t\t\tchk1 = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//아이디 유효성검사\r\n");
      out.write("\t\telse if(!getIdCheck.test($(\"#user_id\").val())){\r\n");
      out.write("\t\t\t$('#user_id').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#idChk').html('<b style=\"font-size:14px;color:red;\">[영문자,숫자 4-14자]</b>');\t  \r\n");
      out.write("\t\t\tchk1 = false;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t//ID 중복확인 비동기 처리\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\t//ID 중복확인 비동기 통신\r\n");
      out.write("\t\t\tconst id = $(this).val();\r\n");
      out.write("\t\t\tconsole.log(id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\turl: \"/user/checkId\",\t\r\n");
      out.write("\t\t\t\theaders: {\r\n");
      out.write("\t                \"Content-Type\": \"application/json\"\r\n");
      out.write("\t            },\r\n");
      out.write("\t\t\t\tdataType: \"text\",\r\n");
      out.write("\t\t\t\tdata: id,\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\tif(result === \"OK\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#user_id\").css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#idChk\").html(\"<b style='font-size:14px; color:green;'>[아이디는 사용 가능!]</b>\");\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tchk1 = true;\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$(\"#user_id\").css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#idChk\").html(\"<b style='font-size:14px; color:red;'>[아이디가 중복됨!]</b>\");\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tchk1 = false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function() {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"통신 실패!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//패스워드 입력값 검증.\r\n");
      out.write("\t$('#password').on('keyup', function() {\r\n");
      out.write("\t\t//비밀번호 공백 확인\r\n");
      out.write("\t\tif($(\"#password\").val() === \"\"){\r\n");
      out.write("\t\t    $('#password').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwChk').html('<b style=\"font-size:14px;color:red;\">[패스워드는 필수정보!]</b>');\r\n");
      out.write("\t\t\tchk2 = false;\r\n");
      out.write("\t\t}\t\t         \r\n");
      out.write("\t\t//비밀번호 유효성검사\r\n");
      out.write("\t\telse if(!getPwCheck.test($(\"#password\").val()) || $(\"#password\").val().length < 8){\r\n");
      out.write("\t\t    $('#password').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwChk').html('<b style=\"font-size:14px;color:red;\">[특수문자 포함 8자이상]</b>');\r\n");
      out.write("\t\t\tchk2 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#password').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#pwChk').html('<b style=\"font-size:14px;color:green;\">[참 잘했어요]</b>');\r\n");
      out.write("\t\t\tchk2 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//패스워드 확인란 입력값 검증.\r\n");
      out.write("\t$('#password_check').on('keyup', function() {\r\n");
      out.write("\t\t//비밀번호 확인란 공백 확인\r\n");
      out.write("\t\tif($(\"#password_check\").val() === \"\"){\r\n");
      out.write("\t\t    $('#password_check').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwChk2').html('<b style=\"font-size:14px;color:red;\">[패스워드확인은 필수정보!]</b>');\r\n");
      out.write("\t\t\tchk3 = false;\r\n");
      out.write("\t\t}\t\t         \r\n");
      out.write("\t\t//비밀번호 확인란 유효성검사\r\n");
      out.write("\t\telse if($(\"#password\").val() != $(\"#password_check\").val()){\r\n");
      out.write("\t\t    $('#password_check').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwChk2').html('<b style=\"font-size:14px;color:red;\">[위에랑 똑같이!!]</b>');\r\n");
      out.write("\t\t\tchk3 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#password_check').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#pwChk2').html('<b style=\"font-size:14px;color:green;\">[참 잘했어요]</b>');\r\n");
      out.write("\t\t\tchk3 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//이름 입력값 검증.\r\n");
      out.write("\t$('#user_name').on('keyup', function() {\r\n");
      out.write("\t\t//이름값 공백 확인\r\n");
      out.write("\t\tif($(\"#user_name\").val() === \"\"){\r\n");
      out.write("\t\t    $('#user_name').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#nameChk').html('<b style=\"font-size:14px;color:red;\">[이름은 필수정보!]</b>');\r\n");
      out.write("\t\t\tchk4 = false;\r\n");
      out.write("\t\t}\t\t         \r\n");
      out.write("\t\t//이름값 유효성검사\r\n");
      out.write("\t\telse if(!getName.test($(\"#user_name\").val())){\r\n");
      out.write("\t\t    $('#user_name').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#nameChk').html('<b style=\"font-size:14px;color:red;\">[이름은 한글로 ~]</b>');\r\n");
      out.write("\t\t\tchk4 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#user_name').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#nameChk').html('<b style=\"font-size:14px;color:green;\">[참 잘했어요]</b>');\r\n");
      out.write("\t\t\tchk4 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#signup-btn').click(function(e) {\r\n");
      out.write("\t\tif(chk1 && chk2 && chk3 && chk4) {\r\n");
      out.write("\t\t\t//아이디 정보\r\n");
      out.write("\t\t\tconst id = $(\"#user_id\").val();\r\n");
      out.write("\t\t\tconsole.log(\"id: \" + id);\r\n");
      out.write("\t\t\t//패스워드 정보\r\n");
      out.write("\t\t\tconst pw = $(\"#password\").val();\r\n");
      out.write("\t\t\tconsole.log(\"pw: \" + pw);\r\n");
      out.write("\t\t\t//이름 정보\r\n");
      out.write("\t\t\tconst name = $(\"#user_name\").val();\r\n");
      out.write("\t\t\tconsole.log(\"name: \" + name);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconst user = {\r\n");
      out.write("\t\t\t\taccount: id,\r\n");
      out.write("\t\t\t\tpassword: pw,\r\n");
      out.write("\t\t\t\tname: name\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//클라이언트에서 서버와 통신하는 ajax함수(비동기 통신) \r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"POST\", //서버에 전송하는 HTTP요청 방식\r\n");
      out.write("\t\t\t\turl: \"/user/\", //서버 요청 URI\r\n");
      out.write("\t\t\t\theaders: {\r\n");
      out.write("\t\t\t\t\t\"Content-Type\": \"application/json\"\r\n");
      out.write("\t\t\t\t}, //요청 헤더 정보\r\n");
      out.write("\t\t\t\tdataType: \"text\", //응답받을 데이터의 형태\r\n");
      out.write("\t\t\t\tdata: JSON.stringify(user), //서버로 전송할 데이터\r\n");
      out.write("\t\t\t\tsuccess: function(result) { //함수의 매개변수는 통신성공시의 데이터가 저장될 곳.\r\n");
      out.write("\t\t\t\t\tconsole.log(\"통신 성공!: \" + result);\r\n");
      out.write("\t\t\t\t\tif(result === \"joinSuccess\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"회원가입에 성공했습니다!\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"/\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\talert(\"회원가입에 실패했습니다!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, //통신 성공시 처리할 내용들을 함수 내부에 작성.\r\n");
      out.write("\t\t\t\terror: function() {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"통신 실패!\");\r\n");
      out.write("\t\t\t\t} //통신 실패 시 처리할 내용들을 함수 내부에 작성.\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert('입력정보를 다시 확인하세요.');\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t///////////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\r\n");
      out.write("\t//로그인 검증~~\r\n");
      out.write("\t//ID 입력값 검증.\r\n");
      out.write("\t$('#signInId').on('keyup', function() {\r\n");
      out.write("\t\tif($(\"#signInId\").val() == \"\"){\r\n");
      out.write("\t\t\t$('#signInId').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#idCheck').html('<b style=\"font-size:14px;color:red;\">[아이디는 필수!]</b>');\r\n");
      out.write("\t\t\tchk1 = false;\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//아이디 유효성검사\r\n");
      out.write("\t\telse if(!getIdCheck.test($(\"#signInId\").val())){\r\n");
      out.write("\t\t\t$('#signInId').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#idCheck').html('<b style=\"font-size:14px;color:red;\">[영문자,숫자 4-14자~]</b>');\t  \r\n");
      out.write("\t\t\tchk1 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#signInId').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#idCheck').html('<b style=\"font-size:14px;color:green;\">[참 잘했어요]</b>');\r\n");
      out.write("\t\t\tchk1 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//패스워드 입력값 검증.\r\n");
      out.write("\t$('#signInPw').on('keyup', function() {\r\n");
      out.write("\t\t//비밀번호 공백 확인\r\n");
      out.write("\t\tif($(\"#signInPw\").val() === \"\"){\r\n");
      out.write("\t\t    $('#signInPw').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwCheck').html('<b style=\"font-size:14px;color:red;\">[패스워드는 필수!]</b>');\r\n");
      out.write("\t\t\tchk2 = false;\r\n");
      out.write("\t\t}\t\t         \r\n");
      out.write("\t\t//비밀번호 유효성검사\r\n");
      out.write("\t\telse if(!getPwCheck.test($(\"#signInPw\").val()) || $(\"#signInPw\").val().length < 8){\r\n");
      out.write("\t\t    $('#signInPw').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwCheck').html('<b style=\"font-size:14px;color:red;\">[특수문자 포함 8자이상]</b>');\r\n");
      out.write("\t\t\tchk2 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#signInPw').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#pwCheck').html('<b style=\"font-size:14px;color:green;\">[참 잘했어요]</b>');\r\n");
      out.write("\t\t\tchk2 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//로그인 버튼 클릭이벤트\r\n");
      out.write("\t$(\"#signIn-btn\").click(function() {\r\n");
      out.write("\t\tif(chk1 && chk2) {\r\n");
      out.write("\t\t\t//ajax통신으로 서버에서 값 받아오기\r\n");
      out.write("\t\t\tconst id = $('#signInId').val();\r\n");
      out.write("\t\t\tconst pw = $('#signInPw').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(\"id: \" + id);\r\n");
      out.write("\t\t\tconsole.log(\"pw: \" + pw);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconst userInfo = {\r\n");
      out.write("\t\t\t\t\taccount : id,\r\n");
      out.write("\t\t\t\t\tpassword : pw\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\turl: \"/user/loginCheck\",\r\n");
      out.write("\t\t\t\theaders: {\r\n");
      out.write("\t                \"Content-Type\": \"application/json\"\r\n");
      out.write("\t            },\r\n");
      out.write("\t\t\t\tdata: JSON.stringify(userInfo),\r\n");
      out.write("\t\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"result: \" + result);\t\r\n");
      out.write("\t\t\t\t\tif(result === \"idFail\") {\r\n");
      out.write("\t\t\t\t\t\t$('#signInId').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t\t\t\t$('#idCheck').html('<b style=\"font-size:14px;color:red;\">[회원가입 먼저~~]</b>');\r\n");
      out.write("\t\t\t\t\t\t$('#signInPw').val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#signInId').focus();\r\n");
      out.write("\t\t\t\t\t\tchk2 = false;\r\n");
      out.write("\t\t\t\t    } else if(result === \"pwFail\") {\r\n");
      out.write("\t\t\t\t\t\t$('#signInPw').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t\t\t\t$('#signInPw').val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#signInPw').focus();\r\n");
      out.write("\t\t\t\t\t\t$('#pwCheck').html('<b style=\"font-size:14px;color:red;\">[비밀번호가 틀렸어요!]</b>');\r\n");
      out.write("\t\t\t\t\t\tchk2 = false;\r\n");
      out.write("\t\t\t\t\t} else if(result === \"loginSuccess\") {\r\n");
      out.write("\t\t\t\t\t\tself.location=\"/\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"입력정보를 다시 확인하세요!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 로그인 버튼 클릭 이벤트\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});//end JQuery\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/include/header.jsp(18,31) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/vendor/bootstrap/css/bootstrap.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/include/header.jsp(21,47) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/vendor/fontawesome-free/css/all.min.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/include/header.jsp(28,31) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/css/agency.min.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/include/header.jsp(31,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/vendor/jquery/jquery.min.js");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/include/header.jsp(32,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/vendor/bootstrap/js/bootstrap.bundle.min.js");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/include/header.jsp(36,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/vendor/jquery-easing/jquery.easing.min.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/include/header.jsp(40,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/js/jqBootstrapValidation.js");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/include/header.jsp(74,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/img/mark.png");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/views/include/header.jsp(87,56) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/introduce");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /WEB-INF/views/include/header.jsp(112,56) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/board/list");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/include/header.jsp(114,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          <li class=\"nav-item\">\r\n");
          out.write("            <a class=\"nav-link js-scroll-trigger\" data-toggle=\"modal\" data-target=\"#log-in\">LOGIN</a>\r\n");
          out.write("          </li>\r\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/include/header.jsp(119,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          <li class=\"nav-item\">\r\n");
          out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"#\">MYPAGE</a>\r\n");
          out.write("          </li>\r\n");
          out.write("          <li class=\"nav-item\">\r\n");
          out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"/user/logout\" onclick=\"return confirm('진짜로 로그아웃 하는거에요?')\">LOGOUT</a>\r\n");
          out.write("          </li>\r\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/include/header.jsp(136,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <button class=\"btn btn-chu btn-xl text-uppercase js-scroll-trigger\" data-toggle=\"modal\" data-target=\"#log-in\">CHU~♥</button>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/include/header.jsp(139,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    \t <a class=\"btn btn-chu btn-xl text-uppercase js-scroll-trigger\" href=\"#\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 안녕~♥</a>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
