/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-10-27 08:32:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/board/../include/../users/login_modal.jspf", Long.valueOf(1603427908228L));
    _jspx_dependants.put("jar:file:/C:/Users/82105/TIL/2020/October%202020/JSP/apache-tomcat-9.0.39/wtpwebapps/MyFirstWeb/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1603678297659L));
    _jspx_dependants.put("/board/../include/header.jspf", Long.valueOf(1603695923565L));
    _jspx_dependants.put("jar:file:/C:/Users/82105/TIL/2020/October%202020/JSP/apache-tomcat-9.0.39/wtpwebapps/MyFirstWeb/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/board/../include/footer.jspf", Long.valueOf(1603347013052L));
    _jspx_dependants.put("/board/../include/../music/music_modal.jspf", Long.valueOf(1603347013064L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	String userSessionName = (String)session.getAttribute("user_name");
	String userSessionId = (String)session.getAttribute("user_id");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <title>아이즈원츄~CHU~♡</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"/izone/static/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom fonts for this template -->\r\n");
      out.write("  <link href=\"/izone/static/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"/izone/static/css/agency.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"/izone/static/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/izone/static/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  <!-- Plugin JavaScript -->\r\n");
      out.write("  <script src=\"/izone/static/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Contact form JavaScript -->\r\n");
      out.write("  <script src=\"/izone/static/js/jqBootstrapValidation.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".music-menu {\r\n");
      out.write("\tbackground-color: #ff52a0;\r\n");
      out.write("\tborder: 1px solid #fffe2e;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".music-tap {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write(".music-tap:hover {\r\n");
      out.write("    background-color: #ff52a0;\r\n");
      out.write("    color: #F7FE2E;\r\n");
      out.write("    text-shadow: 5px 2px 2px black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover > .dropdown-menu { \r\n");
      out.write("    display: block;  \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-light fixed-top\" id=\"mainNav\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"/izone\">\r\n");
      out.write("      \t<img class=\"img-fluid\" src=\"/izone/static/img/mark.png\" alt=\"\" style=\"width:130px; height:50px;\" />\r\n");
      out.write("      </a>\r\n");
      out.write("      <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\">\r\n");
      out.write("        메뉴\r\n");
      out.write("        <i class=\"fas fa-bars\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("        <ul class=\"navbar-nav text-uppercase ml-auto\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"/izone\">HOME</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"/izone/introduce/introduce.jsp\">INTRODUCE</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger dropdown-toggle\" data-toggle=\"dropdown\">MUSIC</a>\r\n");
      out.write("            <div class=\"dropdown-menu music-menu\"> \r\n");
      out.write("            \r\n");
      out.write("              <div class=\"dropdown dropright\">            \r\n");
      out.write("\t\t        <a class=\"dropdown-item dropdown-toggle music-tap\" data-toggle=\"dropdown\" style=\"color:white;\">COLOR*IZ</a>\r\n");
      out.write("\t\t\t    <div class=\"dropdown-menu music-menu\"> \r\n");
      out.write("\t\t\t      <a class=\"dropdown-item music-tap\" data-toggle=\"modal\" href=\"#lavieenrose\">La Vie En Rose MV</a>\r\n");
      out.write("\t\t\t      <a class=\"dropdown-item music-tap\" data-toggle=\"modal\" href=\"#lavieenrose-2\">La Vie En Rose 교차편집</a>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t      <div class=\"dropdown dropright\">            \r\n");
      out.write("\t\t        <a class=\"dropdown-item dropdown-toggle music-tap\" data-toggle=\"dropdown\" style=\"color:white;\">HEART*IZ</a>\r\n");
      out.write("\t\t\t    <div class=\"dropdown-menu music-menu\"> \r\n");
      out.write("\t\t\t      <a class=\"dropdown-item music-tap\" data-toggle=\"modal\" href=\"#violeta\">Violeta MV</a>\r\n");
      out.write("\t\t\t      <a class=\"dropdown-item music-tap\" data-toggle=\"modal\" href=\"#violeta-2\">Violeta 교차편집</a>\t\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      \t   \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"/izone/board/Blist.izone\">BOARD</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          ");
 if(userSessionName == null) { 
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" data-toggle=\"modal\" data-target=\"#log-in\">LOGIN</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          ");
 } else { 
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"/izone/users/mypage_change_pw.jsp\">MYPAGE</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"/izone/users/logout.jsp\" onclick=\"return confirm('진짜로 로그아웃 하는거에요?')\">LOGOUT</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav><br><br><br>\r\n");
      out.write("\r\n");
      out.write("  <!-- Header -->\r\n");
      out.write("  <header class=\"masthead\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"intro-text\">        \r\n");
      out.write("    ");
 if(userSessionName == null) { 
      out.write("\r\n");
      out.write("        <button class=\"btn btn-chu btn-xl text-uppercase js-scroll-trigger\" data-toggle=\"modal\" data-target=\"#log-in\">CHU~♥</button>\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("    \t <a class=\"btn btn-chu btn-xl text-uppercase js-scroll-trigger\" href=\"/izone/users/mypage_change_pw.jsp\">");
      out.print(userSessionName );
      out.write("님 안녕~♥</a>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 Modal-->\r\n");
      out.write("<div class=\"modal fade\" id=\"log-in\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: #ff52a0;\">IZONE</span> 로그인\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"/izone/users/check_login.jsp\" name=\"izone-sign-in\" method=\"post\" id=\"signInForm\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-bottom: 0;\">\r\n");
      out.write("\t\t\t\t\t<table style=\"cellpadding: 0; cellspacing: 0; margin: 0 auto; width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>아이디를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"idCheck\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"signInId\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control tooltipstered\" maxlength=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"최대 10자\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>비밀번호를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"pwCheck\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" size=\"17\" maxlength=\"20\" id=\"signInPw\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"userPw\" class=\"form-control tooltipstered\" \r\n");
      out.write("\t\t\t\t\t\t\t\tmaxlength=\"20\" required=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"ime-mode: inactive; margin-bottom: 25px; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"최소 8자\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-top: 10px; text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>로그인하셔서 WIZONE이 되어보세요~~!</strong></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 100%; text-align: center; colspan: 2;\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" value=\"로그인\" class=\"btn form-control tooltipstered\" id=\"signIn-btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: #ff52a0; margin-top: 0; height: 40px; color: white; border: 0px solid #f78f24; opacity: 0.8\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%; text-align: center; colspan: 2; margin-top: 24px; padding-top: 12px; border-top: 1px solid #ececec\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn form-control tooltipstered\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#sign-up\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"cursor: pointer; margin-top: 0; height: 40px; color: white; background-color: orange; border: 0px solid #388E3C; opacity: 0.8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 회원가입 Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"sign-up\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Modal content-->\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t<span style=\"color: #ff52a0;\">IZONE</span> 회원 가입\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"/izone/users/join_ok.jsp\" name=\"signup\" id=\"signUpForm\" method=\"post\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-bottom: 0;\">\r\n");
      out.write("\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\tstyle=\"cellpadding: 0; cellspacing: 0; margin: 0 auto; width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>아이디를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"idChk\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"user_id\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control tooltipstered\" maxlength=\"14\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"숫자와 영어로 4-14자\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>비밀번호를 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"pwChk\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" size=\"17\" maxlength=\"20\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"userPw\" class=\"form-control tooltipstered\" \r\n");
      out.write("\t\t\t\t\t\t\t\tmaxlength=\"20\" required=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"ime-mode: inactive; margin-bottom: 25px; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"영문과 특수문자를 포함한 최소 8자\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>비밀번호를 재확인해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"pwChk2\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" size=\"17\" maxlength=\"20\" id=\"password_check\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"pw_check\" class=\"form-control tooltipstered\" \r\n");
      out.write("\t\t\t\t\t\t\t\tmaxlength=\"20\" required=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"ime-mode: inactive; margin-bottom: 25px; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"비밀번호가 일치해야합니다.\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>이름을 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"nameChk\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"userName\" id=\"user_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control tooltipstered\" maxlength=\"6\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"한글로 최대 6자\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>이메일을 입력해주세요.</strong>&nbsp;&nbsp;&nbsp;<span id=\"emailChk\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"email\" name=\"userEmail\" id=\"user_email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control tooltipstered\" \r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" aria-required=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 25px; width: 100%; height: 40px; border: 1px solid #d9d9de\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"ex) izone@produce.com\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-top: 10px; text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><strong>회원가입하셔서 WIZONE이 되어보세요~~!</strong></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 100%; text-align: center; colspan: 2;\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"button\" value=\"회원가입\" \r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn form-control tooltipstered\" id=\"signup-btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: #ff52a0; margin-top: 0; height: 40px; color: white; border: 0px solid #388E3C; opacity: 0.8\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar getIdCheck= RegExp(/^[a-zA-Z0-9]{4,14}$/);\r\n");
      out.write("\tvar getPwCheck= RegExp(/([a-zA-Z0-9].*[!,@,#,$,%,^,&,*,?,_,~])|([!,@,#,$,%,^,&,*,?,_,~].*[a-zA-Z0-9])/);\r\n");
      out.write("\tvar getName= RegExp(/^[가-힣]+$/);\r\n");
      out.write("\tvar getMail = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/);\r\n");
      out.write("\tvar chk1 = false, chk2 = false, chk3 = false, chk4 = false, chk5 = false;\r\n");
      out.write("\t\r\n");
      out.write("\t//회원가입 검증~~\r\n");
      out.write("\t//ID 입력값 검증.\r\n");
      out.write("\t$('#user_id').on('keyup', function() {\r\n");
      out.write("\t\tif($(\"#user_id\").val() == \"\"){\r\n");
      out.write("\t\t\t$('#user_id').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#idChk').html('<b style=\"font-size:16px;color:red;\">[아이디는 필수 정보에요!]</b>');\r\n");
      out.write("\t\t\tchk1 = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//아이디 유효성검사\r\n");
      out.write("\t\telse if(!getIdCheck.test($(\"#user_id\").val())){\r\n");
      out.write("\t\t\t$('#user_id').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#idChk').html('<b style=\"font-size:16px;color:red;\">[영문자,숫자 4-14자로 입력하라구~]</b>');\t  \r\n");
      out.write("\t\t\tchk1 = false;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t//ID 중복확인 비동기 처리\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\turl: \"/izone/users/confirm_id.jsp\",\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\t\"user_id\": $('#user_id').val()\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tif($.trim(data) == \"YES\") {\r\n");
      out.write("\t\t\t\t\t\t$('#user_id').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t\t\t\t$('#idChk').html('<b style=\"font-size:16px;color:green;\">[ID 사용 가능!]</b>');\r\n");
      out.write("\t\t\t\t\t\tchk1 = true;\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$('#user_id').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t\t\t\t$('#idChk').html('<b style=\"font-size:16px;color:red;\">[중복된 ID입니다!]</b>');\r\n");
      out.write("\t\t\t\t\t\tchk1 = false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//패스워드 입력값 검증.\r\n");
      out.write("\t$('#password').on('keyup', function() {\r\n");
      out.write("\t\t//비밀번호 공백 확인\r\n");
      out.write("\t\tif($(\"#password\").val() == \"\"){\r\n");
      out.write("\t\t    $('#password').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwChk').html('<b style=\"font-size:16px;color:red;\">[패스워드는 필수정보에요!]</b>');\r\n");
      out.write("\t\t\tchk2 = false;\r\n");
      out.write("\t\t}\t\t         \r\n");
      out.write("\t\t//비밀번호 유효성검사\r\n");
      out.write("\t\telse if(!getPwCheck.test($(\"#password\").val()) || $(\"#password\").val().length < 8){\r\n");
      out.write("\t\t    $('#password').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwChk').html('<b style=\"font-size:16px;color:red;\">[특수문자 포함 8자이상으루다가~]</b>');\r\n");
      out.write("\t\t\tchk2 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#password').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#pwChk').html('<b style=\"font-size:16px;color:green;\">[참 잘했어요~♡]</b>');\r\n");
      out.write("\t\t\tchk2 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//패스워드 확인란 입력값 검증.\r\n");
      out.write("\t$('#password_check').on('keyup', function() {\r\n");
      out.write("\t\t//비밀번호 확인란 공백 확인\r\n");
      out.write("\t\tif($(\"#password_check\").val() == \"\"){\r\n");
      out.write("\t\t    $('#password_check').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwChk2').html('<b style=\"font-size:16px;color:red;\">[패스워드확인은 필수정보에요!]</b>');\r\n");
      out.write("\t\t\tchk3 = false;\r\n");
      out.write("\t\t}\t\t         \r\n");
      out.write("\t\t//비밀번호 확인란 유효성검사\r\n");
      out.write("\t\telse if($(\"#password\").val() != $(\"#password_check\").val()){\r\n");
      out.write("\t\t    $('#password_check').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwChk2').html('<b style=\"font-size:16px;color:red;\">[위에랑 똑같이 제대로 써!!]</b>');\r\n");
      out.write("\t\t\tchk3 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#password_check').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#pwChk2').html('<b style=\"font-size:16px;color:green;\">[참 잘했어요~♡]</b>');\r\n");
      out.write("\t\t\tchk3 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//이름 입력값 검증.\r\n");
      out.write("\t$('#user_name').on('keyup', function() {\r\n");
      out.write("\t\t//이름값 공백 확인\r\n");
      out.write("\t\tif($(\"#user_name\").val() == \"\"){\r\n");
      out.write("\t\t    $('#user_name').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#nameChk').html('<b style=\"font-size:16px;color:red;\">[이름은 필수정보에요!]</b>');\r\n");
      out.write("\t\t\tchk4 = false;\r\n");
      out.write("\t\t}\t\t         \r\n");
      out.write("\t\t//이름값 유효성검사\r\n");
      out.write("\t\telse if(!getName.test($(\"#user_name\").val())){\r\n");
      out.write("\t\t    $('#user_name').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#nameChk').html('<b style=\"font-size:16px;color:red;\">[이름은 한글로 쓰세용~]</b>');\r\n");
      out.write("\t\t\tchk4 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#user_name').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#nameChk').html('<b style=\"font-size:16px;color:green;\">[참 잘했어요~♡]</b>');\r\n");
      out.write("\t\t\tchk4 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//이메일 입력값 검증.\r\n");
      out.write("\t$('#user_email').on('keyup', function() {\r\n");
      out.write("\t\t//이메일값 공백 확인\r\n");
      out.write("\t\tif($(\"#user_email\").val() == \"\"){\r\n");
      out.write("\t\t    $('#user_email').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#emailChk').html('<b style=\"font-size:16px;color:red;\">[이메일은 필수정보에요!]</b>');\r\n");
      out.write("\t\t\tchk5 = false;\r\n");
      out.write("\t\t}\t\t         \r\n");
      out.write("\t\t//이메일값 유효성검사\r\n");
      out.write("\t\telse if(!getMail.test($(\"#user_email\").val())){\r\n");
      out.write("\t\t    $('#user_email').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#emailChk').html('<b style=\"font-size:16px;color:red;\">[이메일 형식 몰라?]</b>');\r\n");
      out.write("\t\t\tchk5 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#user_email').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#emailChk').html('<b style=\"font-size:16px;color:green;\">[참 잘했어요~♡]</b>');\r\n");
      out.write("\t\t\tchk5 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#signup-btn').click(function(e) {\r\n");
      out.write("\t\tif(chk1 && chk2 && chk3 && chk4 && chk5) {\r\n");
      out.write("\t\t\tvar answer = confirm('회원가입을 완료하시겠습니까?');\r\n");
      out.write("\t\t\tif(answer) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t$('#signUpForm').submit();\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert('입력정보를 다시 확인하세요.');\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t///////////////////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t\r\n");
      out.write("\t//로그인 검증~~\r\n");
      out.write("\t//ID 입력값 검증.\r\n");
      out.write("\t$('#signInId').on('keyup', function() {\r\n");
      out.write("\t\tif($(\"#signInId\").val() == \"\"){\r\n");
      out.write("\t\t\t$('#signInId').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#idCheck').html('<b style=\"font-size:16px;color:red;\">[아이디는 필수 정보에요!]</b>');\r\n");
      out.write("\t\t\tchk1 = false;\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//아이디 유효성검사\r\n");
      out.write("\t\telse if(!getIdCheck.test($(\"#signInId\").val())){\r\n");
      out.write("\t\t\t$('#signInId').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#idCheck').html('<b style=\"font-size:16px;color:red;\">[영문자,숫자 4-14자로 입력하라구~]</b>');\t  \r\n");
      out.write("\t\t\tchk1 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#signInId').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#idCheck').html('<b style=\"font-size:16px;color:green;\">[참 잘했어요~♡]</b>');\r\n");
      out.write("\t\t\tchk1 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//패스워드 입력값 검증.\r\n");
      out.write("\t$('#signInPw').on('keyup', function() {\r\n");
      out.write("\t\t//비밀번호 공백 확인\r\n");
      out.write("\t\tif($(\"#signInPw\").val() == \"\"){\r\n");
      out.write("\t\t    $('#signInPw').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwCheck').html('<b style=\"font-size:16px;color:red;\">[패스워드는 필수정보에요!]</b>');\r\n");
      out.write("\t\t\tchk2 = false;\r\n");
      out.write("\t\t}\t\t         \r\n");
      out.write("\t\t//비밀번호 유효성검사\r\n");
      out.write("\t\telse if(!getPwCheck.test($(\"#signInPw\").val()) || $(\"#signInPw\").val().length < 8){\r\n");
      out.write("\t\t    $('#signInPw').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t$('#pwCheck').html('<b style=\"font-size:16px;color:red;\">[특수문자 포함 8자이상으루다가~]</b>');\r\n");
      out.write("\t\t\tchk2 = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#signInPw').css(\"background-color\", \"aqua\");\r\n");
      out.write("\t\t\t$('#pwCheck').html('<b style=\"font-size:16px;color:green;\">[참 잘했어요~♡]</b>');\r\n");
      out.write("\t\t\tchk2 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#signIn-btn').click(function(e) {\r\n");
      out.write("\t\tif(chk1 && chk2) {\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\turl: \"/izone/users/check_login.jsp\",\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\t\"user_id\": $('#signInId').val(),\r\n");
      out.write("\t\t\t\t\t\"user_pw\": $('#signInPw').val()\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif($.trim(data) == \"NOT_ID\") {\r\n");
      out.write("\t\t\t\t\t\t$('#signInId').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t\t\t\t$('#idCheck').html('<b style=\"font-size:16px;color:red;\">[회원가입 먼저~~]</b>');\r\n");
      out.write("\t\t\t\t\t\t$('#signInPw').val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#signInId').focus();\r\n");
      out.write("\t\t\t\t\t\tchk2 = false;\r\n");
      out.write("\t\t\t\t    } else if($.trim(data) == \"NOT_PW\") {\r\n");
      out.write("\t\t\t\t\t\t$('#signInPw').css(\"background-color\", \"pink\");\r\n");
      out.write("\t\t\t\t\t\t$('#signInPw').val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$('#signInPw').focus();\r\n");
      out.write("\t\t\t\t\t\t$('#pwCheck').html('<b style=\"font-size:16px;color:red;\">[비밀번호가 틀렸습니다ㅠㅠ]</b>');\r\n");
      out.write("\t\t\t\t\t\tchk2 = false;\r\n");
      out.write("\t\t\t\t\t} else if($.trim(data) == \"LOGIN_OK\") {\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"/izone\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert('입력정보를 다시 확인하세요.');\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("header.masthead {\r\n");
      out.write("\t\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<br/><br/> \r\n");
      out.write(" \r\n");
      out.write("    <!-- Begin Page Content -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t<h2 class=\"page-header\"><span style=\"color: #ff52a0;\">IZONE</span> 자유 게시판\r\n");
      out.write("\t\t\t\t\t<a href=\"/izone/board/BWriteView.izone\" class=\"btn float-right\" style=\"background-color: #ff52a0; margin-top: 0; height: 40px; color: white; border: 0px solid #f78f24; opacity: 0.8\">글쓰기</a>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"background-color: #ff52a0; margin-top: 0; height: 40px; color: white; border: 0px solid #f78f24; opacity: 0.8\">\r\n");
      out.write("\t\t\t\t\t\t\t<th>#번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 페이징 처리 시작 -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination justify-content-center\">\r\n");
      out.write("                       \t<li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"page-link\" href=\"#\" \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-color: #ff52a0; margin-top: 0; height: 40px; color: white; border: 0px solid #f78f24; \"><<</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t    <li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t      <a class=\"page-link\" href=\"#\" \r\n");
      out.write("\t\t\t\t\t      style=\"background-color: #ff52a0; margin-top: 0; height: 40px; color: white; border: 0px solid #f78f24; \">>></a>\r\n");
      out.write("\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t<!-- 페이징 처리 끝 -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <span class=\"copyright\">Copyright &copy; By Soon-Gu HONG 2019</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <ul class=\"list-inline social-buttons\">\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\" style=\"background-color: #ff52a0;\">\r\n");
      out.write("                <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\" style=\"background-color: #ff52a0;\">\r\n");
      out.write("                <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"https://www.instagram.com/soongu_hong/\" style=\"background-color: #ff52a0;\">\r\n");
      out.write("                <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <ul class=\"list-inline quicklinks\">\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\">아이즈원 공식카페</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!-- Modal La Vie en Rose -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"lavieenrose\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">라비앙 로즈 MV</h4>\r\n");
      out.write("        <button class=\"close\" type=\"button\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/WZwr2a_lFWY\"></iframe>\r\n");
      out.write("       \r\n");
      out.write("      </div>      \r\n");
      out.write("     </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Modal La Vie en Rose-2 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"lavieenrose-2\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">라비앙 로즈 교차편집</h4>\r\n");
      out.write("        <button class=\"close\" type=\"button\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/HIaoU5UZghQ\"></iframe>\r\n");
      out.write("  \r\n");
      out.write("      </div>      \r\n");
      out.write("     </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Modal Violeta -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"violeta\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">비올레타 MV</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/6eEZ7DJMzuk\"></iframe>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Modal Violeta-2 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"violeta-2\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">비올레타 교차편집</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/ml_0KpFAEhY\"></iframe>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("   </div>");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /board/board_list.jsp(6,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_name == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<script>\r\n");
          out.write("\t\talert(\"로그인이 필요한 서비스입니다.\");\r\n");
          out.write("\t\tlocation.href='/izone';\r\n");
          out.write("\t</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /board/board_list.jsp(46,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("article");
      // /board/board_list.jsp(46,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${articles.messageList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<tr style=\"color: #ff52a0;\">\r\n");
            out.write("\t\t\t\t\t\t\t<!-- 게시글리스트가 들어갈 행 -->\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.bId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.bName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"/izone/board/BContent.izone?bId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.bId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"color: orange;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.bTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("    \r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.bHit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\t\t\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /board/board_list.jsp(59,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy년 MM월 dd일");
      // /board/board_list.jsp(59,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${article.bDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /board/board_list.jsp(75,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("pageNum");
      // /board/board_list.jsp(75,6) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /board/board_list.jsp(75,6) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${articles.pageTotalCount}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t    <li class=\"page-item\">\r\n");
            out.write("\t\t\t\t\t\t    \t<a class=\"page-link\" style=\"margin-top: 0; height: 40px; color: pink; border: 1px solid pink;\"\r\n");
            out.write("\t\t\t\t\t\t    \thref=\"Blist.izone?page=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t    </li>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
